services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      # Theme files
      - ./wp-content/themes:/var/www/html/wp-content/themes
      # Plugin files
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      # Uploads
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      # Custom PHP configuration
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - wordpress_network

  # WordPress CLI for cron jobs and management
  wpcli:
    image: wordpress:cli
    container_name: wordpress_cli
    restart: always
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    depends_on:
      - wordpress
      - db
    networks:
      - wordpress_network
    entrypoint: sh
    command: -c "sleep infinity"

volumes:
  db_data:

networks:
  wordpress_network:
    driver: bridge
